package com.xtdpotato.xero_delta.trading;

import com.xtdpotato.xero_delta.XeroDelta;
import com.xtdpotato.xero_delta.data.ModDataStorage;
import com.xtdpotato.xero_delta.network.TradingSyncPacket;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.OnDatapackSyncEvent;
import net.neoforged.neoforge.event.entity.player.ItemEntityPickupEvent;
import net.neoforged.neoforge.event.entity.player.PlayerEvent;
import net.neoforged.neoforge.event.server.ServerStoppedEvent;
import net.neoforged.neoforge.event.tick.PlayerTickEvent;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import net.neoforged.neoforge.network.PacketDistributor;
import java.util.*;

/** Server-only automatic, finite world listings generated by recipe-connected acquisitions. */
@EventBusSubscriber(modid = XeroDelta.MOD_ID)
public final class RecipeWorldMarket {
    static final String PURCHASE_DROP = "xero_delta_market_purchase";
    private static final Map<MinecraftServer, State> STATES = new IdentityHashMap<>();
    private RecipeWorldMarket() {}

    private static State state(MinecraftServer server) {
        return STATES.computeIfAbsent(server, ignored -> {
            State value = new State(RecipeSupplyIndex.capture(server));
            value.pending.addAll(RecipeWorldMarketData.get(server).keys());
            return value;
        });
    }

    public static void observe(ServerPlayer player) {
        if (player == null || player.isSpectator()) return;
        State state = state(player.server);
        try {
            RecipeOwnedInventory current = RecipeOwnedInventory.capture(player);
            RecipeWorldMarketData data = RecipeWorldMarketData.get(player.server);
            if (state.rebaseNext.remove(player.getUUID())) {
                data.rebase(player.getUUID(), current.counts);
                return;
            }
            Map<String, Long> gains = data.observe(player.getUUID(), current.counts);
            Map<String, Long> additions = new LinkedHashMap<>();
            gains.forEach((key, amount) -> {
                ItemStack sample = current.samples.get(key);
                if (sample == null) return;
                for (String output : state.index.related(sample))
                    additions.merge(output, amount, RecipeWorldMarketData::saturatedAdd);
            });
            additions.forEach((key, amount) -> {
                ItemStack sample = state.index.outputs.get(key);
                if (sample != null && TradingItemEligibility.canList(player.server, sample)) {
                    data.add(key, sample, amount);
                    state.pending.add(key);
                }
            });
        } catch (RuntimeException | LinkageError exception) {
            if (state.warned.add(player.getUUID())) org.slf4j.LoggerFactory.getLogger(XeroDelta.MOD_ID)
                .warn("Could not snapshot recipe-market ownership for {}; keeping previous counts",
                    player.getGameProfile().getName(), exception);
        }
    }

    /** Call immediately after a market delivery to exclude the purchase from acquisitions. */
    public static void rebaseAfterPurchase(ServerPlayer player) {
        try {
            RecipeWorldMarketData.get(player.server).rebase(player.getUUID(),
                RecipeOwnedInventory.capture(player).counts);
        } catch (RuntimeException | LinkageError exception) {
            state(player.server).rebaseNext.add(player.getUUID());
        }
    }

    public static void purchased(MinecraftServer server, TradingListing listing, int amount) {
        if (!RecipeWorldMarketData.isRecipeListing(listing)) return;
        String key = RecipeWorldMarketData.get(server).purchased(listing.id(), amount);
        if (key != null) state(server).pending.add(key);
    }

    @SubscribeEvent public static void onPlayerTick(PlayerTickEvent.Post event) {
        if (event.getEntity() instanceof ServerPlayer player) observe(player);
    }

    @SubscribeEvent public static void onPickup(ItemEntityPickupEvent.Post event) {
        if (event.getPlayer() instanceof ServerPlayer player) {
            if (event.getItemEntity().getPersistentData().getBoolean(PURCHASE_DROP)) rebaseAfterPurchase(player);
            else observe(player);
        }
    }

    @SubscribeEvent public static void beforePickup(ItemEntityPickupEvent.Pre event) {
        if (event.getPlayer() instanceof ServerPlayer player
            && event.getItemEntity().getPersistentData().getBoolean(PURCHASE_DROP)) observe(player);
    }

    @SubscribeEvent public static void onLogout(PlayerEvent.PlayerLoggedOutEvent event) {
        if (event.getEntity() instanceof ServerPlayer player) observe(player);
    }

    @SubscribeEvent public static void onReload(OnDatapackSyncEvent event) {
        if (event.getPlayer() == null) STATES.remove(event.getPlayerList().getServer());
    }

    @SubscribeEvent public static void onStop(ServerStoppedEvent event) {
        STATES.remove(event.getServer());
    }

    @SubscribeEvent public static void onServerTick(ServerTickEvent.Post event) {
        MinecraftServer server = event.getServer();
        State state = STATES.get(server);
        if (state == null) return;
        RecipeWorldMarketData supply = RecipeWorldMarketData.get(server);
        TradingMarketData market = TradingMarketData.get(server);
        // Bound work per tick even when a large modpack connects thousands of outputs.
        List<String> work = state.pending.stream().limit(64).toList();
        for (String key : work) {
            state.pending.remove(key);
            RecipeWorldMarketData.Supply stock = supply.supply(key);
            UUID id = RecipeWorldMarketData.listingId(key);
            ItemStack sample = state.index.outputs.get(key);
            if (stock == null || stock.remaining() <= 0 || sample == null
                || !TradingItemEligibility.canList(server, sample)) {
                if (market.removeListing(id) != null) state.changed = true;
                continue;
            }
            long unit = TradingRules.normalizeItemValue(
                ModDataStorage.get(server.overworld()).getPriceFor(sample));
            int count = (int) Math.min(stock.remaining(),
                Math.min(Integer.MAX_VALUE, Math.max(1, TradingRules.MAX_CURRENCY / unit)));
            TradingListing old = market.getListing(id);
            long price = unit * count;
            if (old != null && old.stack().getCount() == count && old.price() == price
                && ItemStack.isSameItemSameComponents(old.stack(), sample)) continue;
            TradingListing listing = new TradingListing(id, TradingMarketData.WORLD_ACCOUNT_ID,
                TradingMarketData.WORLD_ACCOUNT_NAME, sample.copyWithCount(count), price, price,
                old == null ? server.overworld().getGameTime() : old.createdAt(),
                RecipeWorldMarketData.publicListingId(key), true, Long.MAX_VALUE / 4);
            if (market.putListing(listing) == null) {
                // Keep accumulated supply while the synchronized market page is full.
                state.pending.add(key);
            } else state.changed = true;
        }
        if (state.changed && server.getTickCount() % 20 == 0) {
            state.changed = false;
            for (ServerPlayer player : server.getPlayerList().getPlayers()) {
                if (player.containerMenu instanceof TradingMenu || player.containerMenu instanceof TradingOperatorMenu)
                    PacketDistributor.sendToPlayer(player, TradingSyncPacket.snapshot(player, "", true));
            }
        }
    }

    private static final class State {
        final RecipeSupplyIndex index;
        final LinkedHashSet<String> pending = new LinkedHashSet<>();
        final Set<UUID> rebaseNext = new HashSet<>();
        final Set<UUID> warned = new HashSet<>();
        boolean changed;
        State(RecipeSupplyIndex index) { this.index = index; }
    }
}
